server:
  port: 8080

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/search_db?currentSchema=public&serverTimezone=Asia/Ho_Chi_Minh
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Tự tạo hoặc cập nhật bảng khi entity thay đổi
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: http://localhost:9200
    # (Nếu Elasticsearch của bạn có username/password, hãy thêm chúng ở đây)
    # username: your-username
    # password: your-password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
