services:
  postgres:
    image: postgres:15
    container_name: inventory_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: inventory-service
    ports:
      - "2001:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d order-service" ]
      interval: 5s
      timeout: 3s
      retries: 5